---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: tag_list
  name: colors
  label: colors
- type: tag_list
  name: sizes
  label: sizes
- name: tags
  type: tag_list
  default: []
  label: tags
pages:
- content/english/products/tracksuits/barcelona-tracksuit-black.md
- content/english/products/tracksuits/barcelona-tracksuit-blue.md
- content/english/products/underwear/victory-secret-5-pieces.md
